command_line:
  - sensor:
      name: UDPpower
      command: "python /config/scripts/powernowudp.py" 
      scan_interval: 2  # Set the interval in seconds
      unit_of_measurement: "Wh"
      value_template: "{{ value }}"
  - sensor:
      name: UDPpowertoday
      command: "python3 /config/scripts/powertodayudp.py"  
      unit_of_measurement: "Wh"
      scan_interval: 60  # Set the interval in seconds
      value_template: '{{ value }}'
